/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as email from "./email";
export type { email };
import type * as openid from "./openid";
export type { openid };
import type * as singleKey from "./singleKey";
export type { singleKey };
