/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IAccount,
  IAccountInterface,
} from "../../../src/interfaces/IAccount";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "module",
        type: "address",
      },
    ],
    name: "isAuthorizedModule",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes",
        name: "newOwner",
        type: "bytes",
      },
    ],
    name: "resetOwner",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IAccount__factory {
  static readonly abi = _abi;
  static createInterface(): IAccountInterface {
    return new Interface(_abi) as IAccountInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IAccount {
    return new Contract(address, _abi, runner) as unknown as IAccount;
  }
}
