/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IRecoveryPolicyVerifier,
  IRecoveryPolicyVerifierInterface,
} from "../../../src/interfaces/IRecoveryPolicyVerifier";

const _abi = [
  {
    inputs: [],
    name: "getPolicyVerifierInfo",
    outputs: [
      {
        internalType: "bytes",
        name: "",
        type: "bytes",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          {
            components: [
              {
                internalType: "address",
                name: "guardianVerifier",
                type: "address",
              },
              {
                internalType: "bytes",
                name: "signer",
                type: "bytes",
              },
            ],
            internalType: "struct Identity",
            name: "guardian",
            type: "tuple",
          },
          {
            internalType: "bytes",
            name: "signature",
            type: "bytes",
          },
        ],
        internalType: "struct Permission[]",
        name: "permissions",
        type: "tuple[]",
      },
      {
        internalType: "uint64[]",
        name: "properties",
        type: "uint64[]",
      },
    ],
    name: "verifyRecoveryPolicy",
    outputs: [
      {
        internalType: "bool",
        name: "succ",
        type: "bool",
      },
      {
        internalType: "uint64",
        name: "weight",
        type: "uint64",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IRecoveryPolicyVerifier__factory {
  static readonly abi = _abi;
  static createInterface(): IRecoveryPolicyVerifierInterface {
    return new Interface(_abi) as IRecoveryPolicyVerifierInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IRecoveryPolicyVerifier {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IRecoveryPolicyVerifier;
  }
}
