/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export interface OpenIDKeyManagerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "batchUpdateOpenIDPublicKey"
      | "deleteOpenIDPublicKey"
      | "getOpenIDPublicKey"
      | "owner"
      | "renounceOwnership"
      | "transferOwnership"
      | "updateOpenIDPublicKey"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "DeleteOpenIdPublicKey"
      | "OwnershipTransferred"
      | "UpdateOpenIDPublicKey"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "batchUpdateOpenIDPublicKey",
    values: [BytesLike[], BytesLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "deleteOpenIDPublicKey",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getOpenIDPublicKey",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateOpenIDPublicKey",
    values: [BytesLike, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "batchUpdateOpenIDPublicKey",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deleteOpenIDPublicKey",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getOpenIDPublicKey",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateOpenIDPublicKey",
    data: BytesLike
  ): Result;
}

export namespace DeleteOpenIdPublicKeyEvent {
  export type InputTuple = [_key: BytesLike];
  export type OutputTuple = [_key: string];
  export interface OutputObject {
    _key: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UpdateOpenIDPublicKeyEvent {
  export type InputTuple = [_key: BytesLike, _publicKey: BytesLike];
  export type OutputTuple = [_key: string, _publicKey: string];
  export interface OutputObject {
    _key: string;
    _publicKey: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface OpenIDKeyManager extends BaseContract {
  connect(runner?: ContractRunner | null): OpenIDKeyManager;
  waitForDeployment(): Promise<this>;

  interface: OpenIDKeyManagerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  batchUpdateOpenIDPublicKey: TypedContractMethod<
    [_keys: BytesLike[], _publicKeys: BytesLike[]],
    [void],
    "nonpayable"
  >;

  deleteOpenIDPublicKey: TypedContractMethod<
    [_key: BytesLike],
    [void],
    "nonpayable"
  >;

  getOpenIDPublicKey: TypedContractMethod<[_key: BytesLike], [string], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  updateOpenIDPublicKey: TypedContractMethod<
    [_key: BytesLike, _publicKey: BytesLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "batchUpdateOpenIDPublicKey"
  ): TypedContractMethod<
    [_keys: BytesLike[], _publicKeys: BytesLike[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "deleteOpenIDPublicKey"
  ): TypedContractMethod<[_key: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getOpenIDPublicKey"
  ): TypedContractMethod<[_key: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateOpenIDPublicKey"
  ): TypedContractMethod<
    [_key: BytesLike, _publicKey: BytesLike],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "DeleteOpenIdPublicKey"
  ): TypedContractEvent<
    DeleteOpenIdPublicKeyEvent.InputTuple,
    DeleteOpenIdPublicKeyEvent.OutputTuple,
    DeleteOpenIdPublicKeyEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "UpdateOpenIDPublicKey"
  ): TypedContractEvent<
    UpdateOpenIDPublicKeyEvent.InputTuple,
    UpdateOpenIDPublicKeyEvent.OutputTuple,
    UpdateOpenIDPublicKeyEvent.OutputObject
  >;

  filters: {
    "DeleteOpenIdPublicKey(bytes32)": TypedContractEvent<
      DeleteOpenIdPublicKeyEvent.InputTuple,
      DeleteOpenIdPublicKeyEvent.OutputTuple,
      DeleteOpenIdPublicKeyEvent.OutputObject
    >;
    DeleteOpenIdPublicKey: TypedContractEvent<
      DeleteOpenIdPublicKeyEvent.InputTuple,
      DeleteOpenIdPublicKeyEvent.OutputTuple,
      DeleteOpenIdPublicKeyEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "UpdateOpenIDPublicKey(bytes32,bytes)": TypedContractEvent<
      UpdateOpenIDPublicKeyEvent.InputTuple,
      UpdateOpenIDPublicKeyEvent.OutputTuple,
      UpdateOpenIDPublicKeyEvent.OutputObject
    >;
    UpdateOpenIDPublicKey: TypedContractEvent<
      UpdateOpenIDPublicKeyEvent.InputTuple,
      UpdateOpenIDPublicKeyEvent.OutputTuple,
      UpdateOpenIDPublicKeyEvent.OutputObject
    >;
  };
}
