/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export interface OpenIDVerifierInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addOpenIDAudience"
      | "batchUpdateOpenIDPublicKey"
      | "deleteOpenIDAudience"
      | "deleteOpenIDPublicKey"
      | "getGuardianVerifierInfo"
      | "getOpenIDPublicKey"
      | "isAudienceValid"
      | "isValidPermission"
      | "isValidPermissions"
      | "isValidSigner"
      | "isValidSigners"
      | "owner"
      | "renounceOwnership"
      | "transferOwnership"
      | "updateOpenIDPublicKey"
      | "validateIDToken"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AddOpenIDAudience"
      | "DeleteOpenIDAudience"
      | "DeleteOpenIdPublicKey"
      | "OwnershipTransferred"
      | "UpdateOpenIDPublicKey"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "addOpenIDAudience",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "batchUpdateOpenIDPublicKey",
    values: [BytesLike[], BytesLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "deleteOpenIDAudience",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "deleteOpenIDPublicKey",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getGuardianVerifierInfo",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getOpenIDPublicKey",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isAudienceValid",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isValidPermission",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isValidPermissions",
    values: [BytesLike, BytesLike[], BytesLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "isValidSigner",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isValidSigners",
    values: [BytesLike[]]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateOpenIDPublicKey",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "validateIDToken",
    values: [BigNumberish, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "addOpenIDAudience",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "batchUpdateOpenIDPublicKey",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deleteOpenIDAudience",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deleteOpenIDPublicKey",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getGuardianVerifierInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getOpenIDPublicKey",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isAudienceValid",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isValidPermission",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isValidPermissions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isValidSigner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isValidSigners",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateOpenIDPublicKey",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "validateIDToken",
    data: BytesLike
  ): Result;
}

export namespace AddOpenIDAudienceEvent {
  export type InputTuple = [_key: BytesLike];
  export type OutputTuple = [_key: string];
  export interface OutputObject {
    _key: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DeleteOpenIDAudienceEvent {
  export type InputTuple = [_key: BytesLike];
  export type OutputTuple = [_key: string];
  export interface OutputObject {
    _key: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DeleteOpenIdPublicKeyEvent {
  export type InputTuple = [_key: BytesLike];
  export type OutputTuple = [_key: string];
  export interface OutputObject {
    _key: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UpdateOpenIDPublicKeyEvent {
  export type InputTuple = [_key: BytesLike, _publicKey: BytesLike];
  export type OutputTuple = [_key: string, _publicKey: string];
  export interface OutputObject {
    _key: string;
    _publicKey: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface OpenIDVerifier extends BaseContract {
  connect(runner?: ContractRunner | null): OpenIDVerifier;
  waitForDeployment(): Promise<this>;

  interface: OpenIDVerifierInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addOpenIDAudience: TypedContractMethod<
    [_key: BytesLike],
    [void],
    "nonpayable"
  >;

  batchUpdateOpenIDPublicKey: TypedContractMethod<
    [_keys: BytesLike[], _publicKeys: BytesLike[]],
    [void],
    "nonpayable"
  >;

  deleteOpenIDAudience: TypedContractMethod<
    [_key: BytesLike],
    [void],
    "nonpayable"
  >;

  deleteOpenIDPublicKey: TypedContractMethod<
    [_key: BytesLike],
    [void],
    "nonpayable"
  >;

  getGuardianVerifierInfo: TypedContractMethod<[], [string], "view">;

  getOpenIDPublicKey: TypedContractMethod<[_key: BytesLike], [string], "view">;

  isAudienceValid: TypedContractMethod<[_key: BytesLike], [boolean], "view">;

  isValidPermission: TypedContractMethod<
    [hash: BytesLike, signer: BytesLike, signature: BytesLike],
    [boolean],
    "view"
  >;

  isValidPermissions: TypedContractMethod<
    [hash: BytesLike, signers: BytesLike[], signatures: BytesLike[]],
    [boolean],
    "view"
  >;

  isValidSigner: TypedContractMethod<[signer: BytesLike], [boolean], "view">;

  isValidSigners: TypedContractMethod<
    [signers: BytesLike[]],
    [boolean],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  updateOpenIDPublicKey: TypedContractMethod<
    [_key: BytesLike, _publicKey: BytesLike],
    [void],
    "nonpayable"
  >;

  validateIDToken: TypedContractMethod<
    [_index: BigNumberish, _data: BytesLike],
    [
      [boolean, bigint, string, string, string] & {
        succ: boolean;
        index: bigint;
        issHash: string;
        subHash: string;
        nonceHash: string;
      }
    ],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addOpenIDAudience"
  ): TypedContractMethod<[_key: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "batchUpdateOpenIDPublicKey"
  ): TypedContractMethod<
    [_keys: BytesLike[], _publicKeys: BytesLike[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "deleteOpenIDAudience"
  ): TypedContractMethod<[_key: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "deleteOpenIDPublicKey"
  ): TypedContractMethod<[_key: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getGuardianVerifierInfo"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getOpenIDPublicKey"
  ): TypedContractMethod<[_key: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "isAudienceValid"
  ): TypedContractMethod<[_key: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isValidPermission"
  ): TypedContractMethod<
    [hash: BytesLike, signer: BytesLike, signature: BytesLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "isValidPermissions"
  ): TypedContractMethod<
    [hash: BytesLike, signers: BytesLike[], signatures: BytesLike[]],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "isValidSigner"
  ): TypedContractMethod<[signer: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isValidSigners"
  ): TypedContractMethod<[signers: BytesLike[]], [boolean], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateOpenIDPublicKey"
  ): TypedContractMethod<
    [_key: BytesLike, _publicKey: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "validateIDToken"
  ): TypedContractMethod<
    [_index: BigNumberish, _data: BytesLike],
    [
      [boolean, bigint, string, string, string] & {
        succ: boolean;
        index: bigint;
        issHash: string;
        subHash: string;
        nonceHash: string;
      }
    ],
    "view"
  >;

  getEvent(
    key: "AddOpenIDAudience"
  ): TypedContractEvent<
    AddOpenIDAudienceEvent.InputTuple,
    AddOpenIDAudienceEvent.OutputTuple,
    AddOpenIDAudienceEvent.OutputObject
  >;
  getEvent(
    key: "DeleteOpenIDAudience"
  ): TypedContractEvent<
    DeleteOpenIDAudienceEvent.InputTuple,
    DeleteOpenIDAudienceEvent.OutputTuple,
    DeleteOpenIDAudienceEvent.OutputObject
  >;
  getEvent(
    key: "DeleteOpenIdPublicKey"
  ): TypedContractEvent<
    DeleteOpenIdPublicKeyEvent.InputTuple,
    DeleteOpenIdPublicKeyEvent.OutputTuple,
    DeleteOpenIdPublicKeyEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "UpdateOpenIDPublicKey"
  ): TypedContractEvent<
    UpdateOpenIDPublicKeyEvent.InputTuple,
    UpdateOpenIDPublicKeyEvent.OutputTuple,
    UpdateOpenIDPublicKeyEvent.OutputObject
  >;

  filters: {
    "AddOpenIDAudience(bytes32)": TypedContractEvent<
      AddOpenIDAudienceEvent.InputTuple,
      AddOpenIDAudienceEvent.OutputTuple,
      AddOpenIDAudienceEvent.OutputObject
    >;
    AddOpenIDAudience: TypedContractEvent<
      AddOpenIDAudienceEvent.InputTuple,
      AddOpenIDAudienceEvent.OutputTuple,
      AddOpenIDAudienceEvent.OutputObject
    >;

    "DeleteOpenIDAudience(bytes32)": TypedContractEvent<
      DeleteOpenIDAudienceEvent.InputTuple,
      DeleteOpenIDAudienceEvent.OutputTuple,
      DeleteOpenIDAudienceEvent.OutputObject
    >;
    DeleteOpenIDAudience: TypedContractEvent<
      DeleteOpenIDAudienceEvent.InputTuple,
      DeleteOpenIDAudienceEvent.OutputTuple,
      DeleteOpenIDAudienceEvent.OutputObject
    >;

    "DeleteOpenIdPublicKey(bytes32)": TypedContractEvent<
      DeleteOpenIdPublicKeyEvent.InputTuple,
      DeleteOpenIdPublicKeyEvent.OutputTuple,
      DeleteOpenIdPublicKeyEvent.OutputObject
    >;
    DeleteOpenIdPublicKey: TypedContractEvent<
      DeleteOpenIdPublicKeyEvent.InputTuple,
      DeleteOpenIdPublicKeyEvent.OutputTuple,
      DeleteOpenIdPublicKeyEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "UpdateOpenIDPublicKey(bytes32,bytes)": TypedContractEvent<
      UpdateOpenIDPublicKeyEvent.InputTuple,
      UpdateOpenIDPublicKeyEvent.OutputTuple,
      UpdateOpenIDPublicKeyEvent.OutputObject
    >;
    UpdateOpenIDPublicKey: TypedContractEvent<
      UpdateOpenIDPublicKeyEvent.InputTuple,
      UpdateOpenIDPublicKeyEvent.OutputTuple,
      UpdateOpenIDPublicKeyEvent.OutputObject
    >;
  };
}
