/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export interface DkimKeysInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "batchUpdateDKIMKeys"
      | "deleteDKIMKey"
      | "getDKIMKey"
      | "owner"
      | "renounceOwnership"
      | "transferOwnership"
      | "updateDKIMKey"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "DeleteDKIMKey"
      | "OwnershipTransferred"
      | "UpdateDKIMKey"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "batchUpdateDKIMKeys",
    values: [BytesLike[], BytesLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "deleteDKIMKey",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getDKIMKey",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateDKIMKey",
    values: [BytesLike, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "batchUpdateDKIMKeys",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deleteDKIMKey",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getDKIMKey", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateDKIMKey",
    data: BytesLike
  ): Result;
}

export namespace DeleteDKIMKeyEvent {
  export type InputTuple = [emailServer: BytesLike, oldKey: BytesLike];
  export type OutputTuple = [emailServer: string, oldKey: string];
  export interface OutputObject {
    emailServer: string;
    oldKey: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UpdateDKIMKeyEvent {
  export type InputTuple = [emailServer: BytesLike, key: BytesLike];
  export type OutputTuple = [emailServer: string, key: string];
  export interface OutputObject {
    emailServer: string;
    key: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface DkimKeys extends BaseContract {
  connect(runner?: ContractRunner | null): DkimKeys;
  waitForDeployment(): Promise<this>;

  interface: DkimKeysInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  batchUpdateDKIMKeys: TypedContractMethod<
    [_emailServers: BytesLike[], _keys: BytesLike[]],
    [void],
    "nonpayable"
  >;

  deleteDKIMKey: TypedContractMethod<
    [_emailServer: BytesLike],
    [void],
    "nonpayable"
  >;

  getDKIMKey: TypedContractMethod<[_emailServer: BytesLike], [string], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  updateDKIMKey: TypedContractMethod<
    [_emailServer: BytesLike, key: BytesLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "batchUpdateDKIMKeys"
  ): TypedContractMethod<
    [_emailServers: BytesLike[], _keys: BytesLike[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "deleteDKIMKey"
  ): TypedContractMethod<[_emailServer: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getDKIMKey"
  ): TypedContractMethod<[_emailServer: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateDKIMKey"
  ): TypedContractMethod<
    [_emailServer: BytesLike, key: BytesLike],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "DeleteDKIMKey"
  ): TypedContractEvent<
    DeleteDKIMKeyEvent.InputTuple,
    DeleteDKIMKeyEvent.OutputTuple,
    DeleteDKIMKeyEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "UpdateDKIMKey"
  ): TypedContractEvent<
    UpdateDKIMKeyEvent.InputTuple,
    UpdateDKIMKeyEvent.OutputTuple,
    UpdateDKIMKeyEvent.OutputObject
  >;

  filters: {
    "DeleteDKIMKey(bytes32,bytes)": TypedContractEvent<
      DeleteDKIMKeyEvent.InputTuple,
      DeleteDKIMKeyEvent.OutputTuple,
      DeleteDKIMKeyEvent.OutputObject
    >;
    DeleteDKIMKey: TypedContractEvent<
      DeleteDKIMKeyEvent.InputTuple,
      DeleteDKIMKeyEvent.OutputTuple,
      DeleteDKIMKeyEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "UpdateDKIMKey(bytes32,bytes)": TypedContractEvent<
      UpdateDKIMKeyEvent.InputTuple,
      UpdateDKIMKeyEvent.OutputTuple,
      UpdateDKIMKeyEvent.OutputObject
    >;
    UpdateDKIMKey: TypedContractEvent<
      UpdateDKIMKeyEvent.InputTuple,
      UpdateDKIMKeyEvent.OutputTuple,
      UpdateDKIMKeyEvent.OutputObject
    >;
  };
}
