/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface IAccountInterface extends Interface {
  getFunction(
    nameOrSignature: "isAuthorizedModule" | "resetOwner"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "isAuthorizedModule",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "resetOwner",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "isAuthorizedModule",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "resetOwner", data: BytesLike): Result;
}

export interface IAccount extends BaseContract {
  connect(runner?: ContractRunner | null): IAccount;
  waitForDeployment(): Promise<this>;

  interface: IAccountInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  isAuthorizedModule: TypedContractMethod<
    [module: AddressLike],
    [boolean],
    "nonpayable"
  >;

  resetOwner: TypedContractMethod<[newOwner: BytesLike], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "isAuthorizedModule"
  ): TypedContractMethod<[module: AddressLike], [boolean], "nonpayable">;
  getFunction(
    nameOrSignature: "resetOwner"
  ): TypedContractMethod<[newOwner: BytesLike], [void], "nonpayable">;

  filters: {};
}
