/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface IPermissionVerifierInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "getGuardianVerifierInfo"
      | "isValidPermission"
      | "isValidPermissions"
      | "isValidSigners"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getGuardianVerifierInfo",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isValidPermission",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isValidPermissions",
    values: [BytesLike, BytesLike[], BytesLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "isValidSigners",
    values: [BytesLike[]]
  ): string;

  decodeFunctionResult(
    functionFragment: "getGuardianVerifierInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isValidPermission",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isValidPermissions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isValidSigners",
    data: BytesLike
  ): Result;
}

export interface IPermissionVerifier extends BaseContract {
  connect(runner?: ContractRunner | null): IPermissionVerifier;
  waitForDeployment(): Promise<this>;

  interface: IPermissionVerifierInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getGuardianVerifierInfo: TypedContractMethod<[], [string], "view">;

  isValidPermission: TypedContractMethod<
    [hash: BytesLike, signer: BytesLike, signature: BytesLike],
    [boolean],
    "nonpayable"
  >;

  isValidPermissions: TypedContractMethod<
    [hash: BytesLike, signers: BytesLike[], signatures: BytesLike[]],
    [boolean],
    "nonpayable"
  >;

  isValidSigners: TypedContractMethod<
    [signers: BytesLike[]],
    [boolean],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getGuardianVerifierInfo"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "isValidPermission"
  ): TypedContractMethod<
    [hash: BytesLike, signer: BytesLike, signature: BytesLike],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "isValidPermissions"
  ): TypedContractMethod<
    [hash: BytesLike, signers: BytesLike[], signatures: BytesLike[]],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "isValidSigners"
  ): TypedContractMethod<[signers: BytesLike[]], [boolean], "nonpayable">;

  filters: {};
}
