/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export type IdentityStruct = {
  guardianVerifier: AddressLike;
  signer: BytesLike;
};

export type IdentityStructOutput = [
  guardianVerifier: string,
  signer: string
] & { guardianVerifier: string; signer: string };

export type GuardianInfoStruct = {
  guardian: IdentityStruct;
  property: BigNumberish;
};

export type GuardianInfoStructOutput = [
  guardian: IdentityStructOutput,
  property: bigint
] & { guardian: IdentityStructOutput; property: bigint };

export type ThresholdConfigStruct = {
  threshold: BigNumberish;
  lockPeriod: BigNumberish;
};

export type ThresholdConfigStructOutput = [
  threshold: bigint,
  lockPeriod: bigint
] & { threshold: bigint; lockPeriod: bigint };

export type RecoveryConfigArgStruct = {
  policyVerifier: AddressLike;
  guardianInfos: GuardianInfoStruct[];
  thresholdConfigs: ThresholdConfigStruct[];
};

export type RecoveryConfigArgStructOutput = [
  policyVerifier: string,
  guardianInfos: GuardianInfoStructOutput[],
  thresholdConfigs: ThresholdConfigStructOutput[]
] & {
  policyVerifier: string;
  guardianInfos: GuardianInfoStructOutput[];
  thresholdConfigs: ThresholdConfigStructOutput[];
};

export type PermissionStruct = {
  guardian: IdentityStruct;
  signature: BytesLike;
};

export type PermissionStructOutput = [
  guardian: IdentityStructOutput,
  signature: string
] & { guardian: IdentityStructOutput; signature: string };

export interface IRecoveryAccountInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "DOMAIN_SEPARATOR_NAME"
      | "DOMAIN_SEPARATOR_VERSION"
      | "cancelRecovery"
      | "cancelRecoveryByGuardians"
      | "domainSeparatorV4"
      | "executeRecovery"
      | "getRecoveryConfigs"
      | "getRecoveryNonce"
      | "getRecoveryPolicies"
      | "getRecoveryStatus"
      | "isGuardian"
      | "startRecovery"
      | "updateGuardians"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "GuardiansUpdated"
      | "RecoveryCanceled"
      | "RecoveryExecuted"
      | "RecoveryStarted"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "DOMAIN_SEPARATOR_NAME",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DOMAIN_SEPARATOR_VERSION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "cancelRecovery",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelRecoveryByGuardians",
    values: [AddressLike, PermissionStruct[]]
  ): string;
  encodeFunctionData(
    functionFragment: "domainSeparatorV4",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "executeRecovery",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getRecoveryConfigs",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getRecoveryNonce",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getRecoveryPolicies",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getRecoveryStatus",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isGuardian",
    values: [IdentityStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "startRecovery",
    values: [AddressLike, BytesLike, PermissionStruct[]]
  ): string;
  encodeFunctionData(
    functionFragment: "updateGuardians",
    values: [RecoveryConfigArgStruct[]]
  ): string;

  decodeFunctionResult(
    functionFragment: "DOMAIN_SEPARATOR_NAME",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "DOMAIN_SEPARATOR_VERSION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cancelRecovery",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cancelRecoveryByGuardians",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "domainSeparatorV4",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executeRecovery",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRecoveryConfigs",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRecoveryNonce",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRecoveryPolicies",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRecoveryStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isGuardian", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "startRecovery",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateGuardians",
    data: BytesLike
  ): Result;
}

export namespace GuardiansUpdatedEvent {
  export type InputTuple = [recoveryConfigs: RecoveryConfigArgStruct[]];
  export type OutputTuple = [recoveryConfigs: RecoveryConfigArgStructOutput[]];
  export interface OutputObject {
    recoveryConfigs: RecoveryConfigArgStructOutput[];
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RecoveryCanceledEvent {
  export type InputTuple = [nonce: BigNumberish];
  export type OutputTuple = [nonce: bigint];
  export interface OutputObject {
    nonce: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RecoveryExecutedEvent {
  export type InputTuple = [newOwners: BytesLike, nonce: BigNumberish];
  export type OutputTuple = [newOwners: string, nonce: bigint];
  export interface OutputObject {
    newOwners: string;
    nonce: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RecoveryStartedEvent {
  export type InputTuple = [
    newOwners: BytesLike,
    nonce: BigNumberish,
    expireTime: BigNumberish
  ];
  export type OutputTuple = [
    newOwners: string,
    nonce: bigint,
    expireTime: bigint
  ];
  export interface OutputObject {
    newOwners: string;
    nonce: bigint;
    expireTime: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IRecoveryAccount extends BaseContract {
  connect(runner?: ContractRunner | null): IRecoveryAccount;
  waitForDeployment(): Promise<this>;

  interface: IRecoveryAccountInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  DOMAIN_SEPARATOR_NAME: TypedContractMethod<[], [string], "view">;

  DOMAIN_SEPARATOR_VERSION: TypedContractMethod<[], [string], "view">;

  cancelRecovery: TypedContractMethod<
    [policyVerifier: AddressLike],
    [void],
    "nonpayable"
  >;

  cancelRecoveryByGuardians: TypedContractMethod<
    [policyVerifier: AddressLike, permissions: PermissionStruct[]],
    [void],
    "nonpayable"
  >;

  domainSeparatorV4: TypedContractMethod<[], [string], "view">;

  executeRecovery: TypedContractMethod<
    [policyVerifier: AddressLike],
    [void],
    "nonpayable"
  >;

  getRecoveryConfigs: TypedContractMethod<
    [policyVerifier: AddressLike],
    [RecoveryConfigArgStructOutput],
    "view"
  >;

  getRecoveryNonce: TypedContractMethod<[], [bigint], "view">;

  getRecoveryPolicies: TypedContractMethod<
    [],
    [RecoveryConfigArgStructOutput[]],
    "view"
  >;

  getRecoveryStatus: TypedContractMethod<
    [policyVerifier: AddressLike],
    [[boolean, bigint] & { isRecovering: boolean; expiryTime: bigint }],
    "view"
  >;

  isGuardian: TypedContractMethod<
    [guardian: IdentityStruct],
    [boolean],
    "view"
  >;

  startRecovery: TypedContractMethod<
    [
      policyVerifier: AddressLike,
      newOwner: BytesLike,
      permissions: PermissionStruct[]
    ],
    [void],
    "nonpayable"
  >;

  updateGuardians: TypedContractMethod<
    [configArgs: RecoveryConfigArgStruct[]],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "DOMAIN_SEPARATOR_NAME"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "DOMAIN_SEPARATOR_VERSION"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "cancelRecovery"
  ): TypedContractMethod<[policyVerifier: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "cancelRecoveryByGuardians"
  ): TypedContractMethod<
    [policyVerifier: AddressLike, permissions: PermissionStruct[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "domainSeparatorV4"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "executeRecovery"
  ): TypedContractMethod<[policyVerifier: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getRecoveryConfigs"
  ): TypedContractMethod<
    [policyVerifier: AddressLike],
    [RecoveryConfigArgStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRecoveryNonce"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getRecoveryPolicies"
  ): TypedContractMethod<[], [RecoveryConfigArgStructOutput[]], "view">;
  getFunction(
    nameOrSignature: "getRecoveryStatus"
  ): TypedContractMethod<
    [policyVerifier: AddressLike],
    [[boolean, bigint] & { isRecovering: boolean; expiryTime: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "isGuardian"
  ): TypedContractMethod<[guardian: IdentityStruct], [boolean], "view">;
  getFunction(
    nameOrSignature: "startRecovery"
  ): TypedContractMethod<
    [
      policyVerifier: AddressLike,
      newOwner: BytesLike,
      permissions: PermissionStruct[]
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateGuardians"
  ): TypedContractMethod<
    [configArgs: RecoveryConfigArgStruct[]],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "GuardiansUpdated"
  ): TypedContractEvent<
    GuardiansUpdatedEvent.InputTuple,
    GuardiansUpdatedEvent.OutputTuple,
    GuardiansUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "RecoveryCanceled"
  ): TypedContractEvent<
    RecoveryCanceledEvent.InputTuple,
    RecoveryCanceledEvent.OutputTuple,
    RecoveryCanceledEvent.OutputObject
  >;
  getEvent(
    key: "RecoveryExecuted"
  ): TypedContractEvent<
    RecoveryExecutedEvent.InputTuple,
    RecoveryExecutedEvent.OutputTuple,
    RecoveryExecutedEvent.OutputObject
  >;
  getEvent(
    key: "RecoveryStarted"
  ): TypedContractEvent<
    RecoveryStartedEvent.InputTuple,
    RecoveryStartedEvent.OutputTuple,
    RecoveryStartedEvent.OutputObject
  >;

  filters: {
    "GuardiansUpdated(tuple[])": TypedContractEvent<
      GuardiansUpdatedEvent.InputTuple,
      GuardiansUpdatedEvent.OutputTuple,
      GuardiansUpdatedEvent.OutputObject
    >;
    GuardiansUpdated: TypedContractEvent<
      GuardiansUpdatedEvent.InputTuple,
      GuardiansUpdatedEvent.OutputTuple,
      GuardiansUpdatedEvent.OutputObject
    >;

    "RecoveryCanceled(uint256)": TypedContractEvent<
      RecoveryCanceledEvent.InputTuple,
      RecoveryCanceledEvent.OutputTuple,
      RecoveryCanceledEvent.OutputObject
    >;
    RecoveryCanceled: TypedContractEvent<
      RecoveryCanceledEvent.InputTuple,
      RecoveryCanceledEvent.OutputTuple,
      RecoveryCanceledEvent.OutputObject
    >;

    "RecoveryExecuted(bytes,uint256)": TypedContractEvent<
      RecoveryExecutedEvent.InputTuple,
      RecoveryExecutedEvent.OutputTuple,
      RecoveryExecutedEvent.OutputObject
    >;
    RecoveryExecuted: TypedContractEvent<
      RecoveryExecutedEvent.InputTuple,
      RecoveryExecutedEvent.OutputTuple,
      RecoveryExecutedEvent.OutputObject
    >;

    "RecoveryStarted(bytes,uint256,uint48)": TypedContractEvent<
      RecoveryStartedEvent.InputTuple,
      RecoveryStartedEvent.OutputTuple,
      RecoveryStartedEvent.OutputObject
    >;
    RecoveryStarted: TypedContractEvent<
      RecoveryStartedEvent.InputTuple,
      RecoveryStartedEvent.OutputTuple,
      RecoveryStartedEvent.OutputObject
    >;
  };
}
